# Generated by Django 5.2.11 on 2026-08-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
