# Generated by Django 5.2.11 on 2026-08-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petrating',
            old_name='rating_date',
            new_name='date_rated',
        ),
    ]
